strategies:
  BTC/USD:
    budget: 1000
    buy_confidence: 0.8
    sell_confidence: 1.1
    take_profit: 1.02
    stop_loss: 0.99
    position_scale: 1
    prefetch: 50
    market_buffer: 1024
    data_dump: data/BTC.csv
    debug_dir: debug
    debug_level: 1
    debug_window: 30
    indicator:
      ensemble:
        - weight: 1
          indicator:
            rsi:
              period: 7
              overbought: 0.6
        - weight: 1
          indicator:
            macd:
              fast: 6
              slow: 13
              signal: 5
              buy_threshold: 1.0
              buy_cap: 2
              sell_threshold: 1.0
              sell_cap: -2
              cross_lookback: 1
              ema_warmup: 3
report: report.json
platform:
  alpaca:
    base_url: "https://paper-api.alpaca.markets"
    api_key: "place your api key here"
    secret: "place your secret here"